[project]
authors = ["helehex <helehex@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "number gen"
name = "monums"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "*"
